# Generated by Django 2.0 on 2018-03-28 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0002_auto_20171028_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('COMEDIA', 'Comédia'), ('DOCUMENTARIO', 'Documentário'), ('DRAMA', 'Drama'), ('INFANTIL', 'Infantil'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror')], default='COMEDIA', max_length=100, verbose_name='Gênero'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingresso',
            name='assento',
            field=models.CharField(blank=True, max_length=4, null=True, verbose_name='Assento'),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='meia_entrada',
            field=models.BooleanField(default=False, verbose_name='Meia entrada'),
        ),
        migrations.AddField(
            model_name='ingresso',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cidade',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Cidade'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='cidade',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cinemas', to='cinema.Cidade'),
        ),
        migrations.AlterField(
            model_name='cinema',
            name='nome',
            field=models.CharField(max_length=50, verbose_name='Nome'),
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=255, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='sala',
            name='lotacao',
            field=models.PositiveIntegerField(verbose_name='Lotação'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='fim',
            field=models.DateTimeField(verbose_name='Fim'),
        ),
        migrations.AlterField(
            model_name='sessao',
            name='inicio',
            field=models.DateTimeField(verbose_name='Início'),
        ),
    ]
