# Generated by Django 2.0 on 2018-03-30 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0003_auto_20180328_1413'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('ACAO', 'Ação'), ('COMEDIA', 'Comédia'), ('DOCUMENTARIO', 'Documentário'), ('DRAMA', 'Drama'), ('INFANTIL', 'Infantil'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror')], max_length=100, verbose_name='Gênero'),
        ),
    ]
