# Generated by Django 2.0 on 2018-03-31 03:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cinema', '0004_auto_20180330_2352'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ingresso',
            name='preco',
        ),
        migrations.AddField(
            model_name='sessao',
            name='preco',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='Preço'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='genero',
            field=models.CharField(choices=[('ACAO', 'Ação'), ('AVENTURA', 'Aventura'), ('COMEDIA', 'Comédia'), ('DOCUMENTARIO', 'Documentário'), ('DRAMA', 'Drama'), ('INFANTIL', 'Infantil'), ('ROMANCE', 'Romance'), ('TERROR', 'Terror'), ('OUTRO', 'Outro')], max_length=100, verbose_name='Gênero'),
        ),
    ]
